### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ricokahler** [ricokahler/sanity-super-pane#2]
Edit: this repo has been stale for a little and needs some TLC. This issue represents the work for the stable release of super pane.

- [ ] repo overhaul. get a dev set up working with sanity v3
- [ ] properly rewrite bulk operations so that they work with permissions. support bulk versions of all existing sanity operations
- [ ] rewrite preview mechanism to use sanity preview mechanism more
- [ ] improve column selector and previews integrate it with the above preview mechanism
- [ ] basic filtering
- [ ] advanced filtering
- [ ] sorting
- [ ] bulk editing

**Comment by poorpaddy** [comment]
A cool feature that seems like it would fit in this plugin might be to add a duplicate content.

**Comment by BenjaminWalsh** [comment]
Hey @ricokahler I went to try this out in my project - what I'd like to see is the same formatting - or at least the same options - for functions that configure the results super pane. In this case using a GROQ with existing $id parameter.

```
S.listItem(id)
    .title('Normal List per Band')
    .child(
      createSuperPane(S)
      .schemaType('product')
      .title('Product List')
      .filter(`_type == "product" && references($id)`)
      .params({ id })
      ),
```

vs

```
S.listItem(id)
    .title('Normal List per Band')
    .child(
      createSuperPane('product', S)
      ),
```

I could also make great use of exposing the bulk actions menu to custom document actions as you've mentioned above!

**Comment by jeanpco** [comment]
@ricokahler Hey Rico! 

Where do you stand with that To-do list? Did you ever get around it? If not, and if you need help. I'd like to involve myself. That being said, I've never contributed to anything in the past, so not exactly sure where I'd need to begin. Feel free to reach back by email if ever thats easier jp@field-office.ca
